### ISSUE TITLE
__hash__ and __eq__ should be implemented for Flower

### ISSUE THREAD

**Issue by emesterhazy** [griff4692/coms4444_flowers#12]
If these methods aren't implemented, identical flowers will hash differently, breaking common built in types like dict and set. This is especially problematic since the constructor for `Bouquet` takes a `Dict[Flower, int]`.

There are two simple ways to solve this:

1. Implement `__hash__` and `__eq__` based by calling `hash()` and `==` on the `__str__` implementation for `Flower`
2. Change `Flower` to an immutable dataclass, which gives you hash and eq for free:

```py
@dataclass(eq=True, frozen=True)
class Flower:
    size: FlowerSizes
    color: FlowerColors
    type: FlowerTypes
```

**Comment by emesterhazy** [comment]
FWIW, I think dataclass is the better approach since objects used in hashable types should be immutable (and there's no real reason for `Flower` to be mutable anyways).

**Comment by griff4692** [comment]
Thanks Evan - as always, very on point with code change suggestions!

I think I implemented it but have never used dataclass so let me know if it does look ok.
https://github.com/griff4692/coms4444_flowers/commit/ed298353bdbed53ce2909bdf173d501da0bd3191

**Comment by emesterhazy** [comment]
Looks good to me!
